import type { Plugin, ViteDevServer, ResolvedConfig, UserConfig } from 'vite';

import path from 'node:path';

import type {
  FederalConfig,
  HostConfig,
  ZoneConfig,
  ZoneManifest,
  HostZoneConfig,
  ZoneMatch,
  CreateZoneRouteOptions,
  ZoneRouteModule,
  SharedContainer,
  ProxyMiddlewareOptions,
} from './types';

import {
  RESOLVED_VIRTUAL_HOST_INIT,
  RESOLVED_VIRTUAL_MANIFEST,
  RESOLVED_VIRTUAL_ZONE_ENTRY,
  VIRTUAL_HOST_INIT,
  VIRTUAL_MANIFEST,
  VIRTUAL_ZONE_ENTRY,
} from './constants';
import { loadZoneModule, preloadZoneModule, clearZoneCache } from './host/virtual-loader';
import { matchZone, normalizeBasePath, isZoneAssetRequest } from './host/zone-matcher';
import {
  getSharedContainer,
  initSharedContainer,
  getSharedModule,
  setSharedModule,
  hasSharedModule,
} from './runtime/index';
import { createProxyMiddleware } from './server/proxy-middleware';
import {
  createSharedVirtualModule,
  fromSharedVirtualId,
  isSharedPackage,
  normalizeSharedList,
  toResolvedSharedVirtualId,
} from './shared/externals';
import { generateZoneEntryCode } from './zone/entry-builder';
import {
  createZoneManifest,
  generateManifestVirtualModule,
  generateManifestJson,
} from './zone/manifest';

export type {
  FederalConfig,
  HostConfig,
  ZoneConfig,
  ZoneManifest,
  HostZoneConfig,
  ZoneMatch,
  CreateZoneRouteOptions,
  ZoneRouteModule,
  SharedContainer,
  ProxyMiddlewareOptions,
};

export {
  createProxyMiddleware,
  matchZone,
  normalizeBasePath,
  isZoneAssetRequest,
  loadZoneModule,
  preloadZoneModule,
  clearZoneCache,
  createZoneManifest,
  generateZoneEntryCode,
  createSharedVirtualModule,
  normalizeSharedList,
  getSharedContainer,
  initSharedContainer,
  getSharedModule,
  setSharedModule,
  hasSharedModule,
};

function generateHostInitCode(sharedList: readonly string[]): string {
  const imports: string[] = [];
  const registrations: string[] = [];

  sharedList.forEach(function addPackage(pkg: string, index: number): void {
    const importName = `_shared_${index}`;
    const pkgLiteral = JSON.stringify(pkg);
    imports.push(`import * as ${importName} from ${pkgLiteral};`);
    registrations.push(`container.set(${pkgLiteral}, ${importName});`);
  });

  return `// Host Shared Initializer generated by treez-federal
${imports.join('\n')}

function initSharedContainer() {
  const isBrowser = typeof window !== 'undefined';
  const g = isBrowser ? window : (typeof globalThis !== 'undefined' ? globalThis : self);
  if (g.__TREEZ_FEDERAL_SHARED__) {
    return g.__TREEZ_FEDERAL_SHARED__;
  }

  const modules = Object.create(null);
  const container = {
    version: '1.0.0',
    modules: modules,
    get: function(name) {
      if (name === '__proto__' || name === 'prototype' || name === 'constructor') {
        return undefined;
      }
      return modules[name] !== undefined ? modules[name] : undefined;
    },
    set: function(name, mod) {
      if (name === '__proto__' || name === 'prototype' || name === 'constructor') {
        return;
      }
      modules[name] = mod;
    },
    has: function(name) {
      if (name === '__proto__' || name === 'prototype' || name === 'constructor') {
        return false;
      }
      return Object.prototype.hasOwnProperty.call(modules, name);
    },
    register: function(name, mod) {
      if (name === '__proto__' || name === 'prototype' || name === 'constructor') {
        return;
      }
      modules[name] = mod;
    },
  };

  g.__TREEZ_FEDERAL_SHARED__ = container;
  return container;
}

const container = initSharedContainer();
${registrations.join('\n')}
`;
}

export function federal(config: FederalConfig): Plugin {
  let resolvedConfig: ResolvedConfig | null = null;
  const sharedList: string[] = normalizeSharedList(config.shared);

  if (config.mode === 'host') {
    const hostConfig = config as HostConfig;

    return {
      name: 'treez-federal:host',
      enforce: 'pre',

      config(): UserConfig {
        return {
          optimizeDeps: {
            include: [...sharedList],
            exclude: ['@wanrif/treez-federal/runtime'],
          },
        };
      },

      configResolved(cfg: ResolvedConfig): void {
        resolvedConfig = cfg;
      },

      resolveId(id: string): string | null {
        if (id === VIRTUAL_HOST_INIT) {
          return RESOLVED_VIRTUAL_HOST_INIT;
        }
        return null;
      },

      load(id: string): string | null {
        if (id === RESOLVED_VIRTUAL_HOST_INIT) {
          return generateHostInitCode(sharedList);
        }
        return null;
      },

      transformIndexHtml(html: string): string {
        const scriptTag = `<script type="module" src="/@id/${VIRTUAL_HOST_INIT}"></script>`;
        if (html.includes('<head>')) {
          return html.replace('<head>', `<head>\n    ${scriptTag}`);
        }
        return `${scriptTag}\n${html}`;
      },

      configureServer(server: ViteDevServer): void {
        const proxy = createProxyMiddleware({
          zones: hostConfig.zones,
        });

        server.middlewares.use(proxy);
      },
    };
  }

  const zoneConfig = config as ZoneConfig;
  const normalizedBase = normalizeBasePath(zoneConfig.basePath);
  const baseWithSlash = normalizedBase + '/';
  const manifest = createZoneManifest(zoneConfig);

  return {
    name: 'treez-federal:zone',
    enforce: 'pre',

    config(userConfig: UserConfig): UserConfig {
      const existingExclude = userConfig.optimizeDeps?.exclude
        ? userConfig.optimizeDeps.exclude
        : [];

      return {
        base: baseWithSlash,
        optimizeDeps: {
          exclude: [...existingExclude, ...sharedList],
        },
      };
    },

    configResolved(cfg: ResolvedConfig): void {
      resolvedConfig = cfg;
    },

    resolveId(id: string): string | null {
      if (id === VIRTUAL_ZONE_ENTRY) {
        return RESOLVED_VIRTUAL_ZONE_ENTRY;
      }
      if (id === VIRTUAL_MANIFEST) {
        return RESOLVED_VIRTUAL_MANIFEST;
      }

      if (isSharedPackage(id, sharedList)) {
        return toResolvedSharedVirtualId(id);
      }

      return null;
    },

    load(id: string): string | null {
      if (id === RESOLVED_VIRTUAL_ZONE_ENTRY) {
        const rootDir = resolvedConfig ? resolvedConfig.root : process.cwd();
        const routesFile = zoneConfig.routes ? zoneConfig.routes : './src/routes/index.ts';
        const resolvedRoutesPath = path.isAbsolute(routesFile)
          ? routesFile
          : path.resolve(rootDir, routesFile);

        return generateZoneEntryCode({
          routesPath: resolvedRoutesPath,
          manifest,
        });
      }

      if (id === RESOLVED_VIRTUAL_MANIFEST) {
        return generateManifestVirtualModule(manifest);
      }

      const sharedPkg = fromSharedVirtualId(id);
      if (sharedPkg) {
        return createSharedVirtualModule(sharedPkg);
      }

      return null;
    },

    configureServer(server: ViteDevServer): void {
      const entryRoute = `${normalizedBase}/zoneEntry.js`;

      server.middlewares.use(function handleZoneEntry(req, res, next): void {
        const url = req.url ? req.url.split('?')[0] : '';
        if (url === entryRoute || url === '/zoneEntry.js') {
          server
            .transformRequest(VIRTUAL_ZONE_ENTRY)
            .then(function sendTransformed(result): void {
              if (result) {
                res.statusCode = 200;
                res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
                res.setHeader('Cache-Control', 'no-cache');
                res.end(result.code);
              } else {
                next();
              }
            })
            .catch(function onError(err: unknown): void {
              next(err);
            });
          return;
        }
        next();
      });
    },

    generateBundle(): void {
      this.emitFile({
        type: 'asset',
        fileName: 'manifest.json',
        source: generateManifestJson(manifest),
      });
    },
  };
}
