import type { ZoneManifest } from '../types';

export function generateZoneEntryCode(options: {
  routesPath: string;
  manifest?: ZoneManifest;
}): string {
  const routesImport = options.routesPath.replace(/\\/g, '/');
  const manifestJson = options.manifest ? JSON.stringify(options.manifest, null, 2) : '{}';

  return `// Generated by treez-federal entry-builder
import { createZoneRoutes as _createZoneRoutes } from ${JSON.stringify(routesImport)};

export const createZoneRoutes = _createZoneRoutes;
export const manifest = ${manifestJson};

export default {
  createZoneRoutes,
  manifest,
};
`;
}
